### ISSUE TITLE
very important suggestion.

### ISSUE THREAD

**Issue by didntpot** [NhanAZ/AntiPoggitStaff#10]
how about, instead of banning the poggit staff as the plugin starts, ban them on join for "dragonfly supremacy"!

**Comment by didntpot** [comment]
~~i know its a waste of resources on kick/ban someone on join~~

**Comment by didntpot** [comment]
@NhanAZ very important suggestion here!

**Comment by HBIDamian** [comment]
This plugin is for PokketMien-Em-Pea!
Promoting other software is blasphemy!
