### ISSUE TITLE
No longer reviewer

### ISSUE THREAD

**Issue by Gewinum** [NhanAZ/AntiPoggitStaff#19]
feel free to get me off this list im no longer reviewer xd

**Comment by Gewinum** [comment]
@NhanAZ

**Comment by NhanAZ** [comment]
I'm wondering about amnesty for those who contributed to Poggit

**Comment by Gewinum** [comment]
> I'm wondering about amnesty for those who contributed to Poggit

what do you mean amnesty though?

**Comment by Gewinum** [comment]
> I'm wondering about amnesty for those who contributed to Poggit

there's high chance that i won't be back at poggit. feel free to delete me out of the list

**Comment by NhanAZ** [comment]
Please find another username to take your place

**Comment by Gewinum** [comment]
> Please find another username to take your place

whats the purpose?

**Comment by HBIDamian** [comment]
Impersonating a poggit user will cause your next poggit user to be flagged by the AntiPoggitStaff Anti Poggit Staff members.

**Comment by skyss0fly** [comment]
Do we still need this open?

**Comment by HBIDamian** [comment]
Not anymore. Since #20, I've hired a Chef to speak to my lead biologist to come up with the best meal to fix our problems.
