### ISSUE TITLE
Faulty Plugin

### ISSUE THREAD

**Issue by ethaniccc** [NhanAZ/AntiPoggitStaff#3]
You got my minecraft username wrong and therefore this plugin is ineffective. I will now have to ratio and cancel you on Twitter if this is not fixed within the next few hours.

**Comment by HBIDamian** [comment]
Dear \<Insert name here\>, 
We have received your issue and have came up with a way to rectify it. If you supply us with the correct username, we shall fix the issue!
Thanks, 
Damian (Flappyboobs) Mctitties

**Comment by ethaniccc** [comment]
Damn, I love titties so I'm therefore obligated to give what you request.

My usernames are: coEthaniccc, Epicthic, SpaceLostC9909, egirlonvalorant

**Comment by HBIDamian** [comment]
Done.
https://github.com/NhanAZ/AntiPoggitStaffs/commit/9afcb2a7b9f871ee372b5d71c80feed0689385ae
