### ISSUE TITLE
Mega ban

### ISSUE THREAD

**Issue by NgLam2911** [NhanAZ/AntiPoggitStaff#6]
* Ban every plugin developer at poggit because their plugin got APPROVED !!!!

**Comment by NhanAZ** [comment]
This is crazy! It would ban myself...
Anyway... I deserve to be banned from submitting plugins to poggit!!

**Comment by NhanAZ** [comment]
Super Mega Ultra Issue!!

**Comment by dadevguy** [comment]
um

**Comment by dadevguy** [comment]
> Super Mega Ultra Issue!!

how will u get all developers name lol

**Comment by NhanAZ** [comment]
> how will u get all developers name lol

Here: https://poggit.pmmp.io/releases.json

**Comment by dadevguy** [comment]
> > how will u get all developers name lol
> 
> Here: https://poggit.pmmp.io/releases.json

ok ._.

**Comment by NhanAZ** [comment]
A new plugin should be made for this idea.
This plugin only hates poggit staff, not poggit developers.
Thanks for your very creative idea!
