### ISSUE TITLE
Remove approved plugins from poggit

### ISSUE THREAD

**Issue by Mcbeany** [NhanAZ/AntiPoggitStaff#7]
Identity: Have `.poggit.yml` file in their plugin and check if it has been approved by poggit

**Comment by NhanAZ** [comment]
I'm quite worried
because poggit's staff owns a lot of important plugins :rofl:

**Comment by NhanAZ** [comment]
Should be implemented in another plugin. I just really hate poggit's staff.
Anyway, thanks for the suggestion.
